
[functions.compliance-review]
enabled = true
verify_jwt = true
import_map = "./functions/compliance-review/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compliance-review/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compliance-review/*.html" ]

[functions.deel-api]
enabled = true
verify_jwt = true
import_map = "./functions/deel-api/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deel-api/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deel-api/*.html" ]

[auth]
# Additional redirect URLs for local development
# Uncomment and use with: supabase start
# additional_redirect_urls = [
#   "http://localhost:5173/auth/callback",
#   "http://localhost:3000/auth/callback",
#   "http://localhost:8081/auth/callback"
# ]
